services:
  mytest:
    build:
      context: ./eb-test
      dockerfile: docker/Dockerfile
    image: mytest:v3.0.0
    container_name: mytest
    ports:
      - "9001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mytest.rule=Host(`test.dev.ci.org`)"
      - "traefik.http.routers.mytest.entrypoints=http"
      - "traefik.http.services.mytest.loadbalancer.server.port=9001"
    networks:
      - coolify

networks:
  coolify:
    external: true