services:
  mytest:
    build:
        context: ./
        dockerfile: Dockerfile
    image: mytest:v3.0.0
    container_name: mytest
    ports:
      - 8081:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`test.dev.ci.org`)"
      - "traefik.http.routers.app.entrypoints=http"
      - "traefik.http.services.app.loadbalancer.server.port=8080"